# Generated by Django 4.1.4 on 2023-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_curso_fecha_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Instituto',
        ),
    ]
